use crate::d_event::*;
use crate::d_items::*;
use crate::d_net::*;
use crate::d_player::*;
use crate::d_think::*;
use crate::d_ticcmd::*;
use crate::doomdata::*;
use crate::doomdef::*;
use crate::doomstat::*;
use crate::doomtype::*;
use crate::g_game::*;
use crate::i_system::*;
use crate::info::*;
use crate::m_fixed::*;
use crate::p_local::*;
use crate::p_mobj::*;
use crate::p_pspr::*;
use crate::p_spec::*;
use crate::r_bsp::*;
use crate::r_data::*;
use crate::r_defs::*;
use crate::r_draw::*;
use crate::r_local::*;
use crate::r_main::*;
use crate::r_plane::*;
use crate::r_segs::*;
use crate::r_state::*;
use crate::r_things::*;
use crate::s_sound::*;
use crate::sounds::*;
use crate::tables::*;

static mut rcsid: [std::ffi::c_char; 51] = unsafe {
    [
        36 as std::ffi::c_char,
        73 as std::ffi::c_char,
        100 as std::ffi::c_char,
        58 as std::ffi::c_char,
        32 as std::ffi::c_char,
        112 as std::ffi::c_char,
        95 as std::ffi::c_char,
        115 as std::ffi::c_char,
        119 as std::ffi::c_char,
        105 as std::ffi::c_char,
        116 as std::ffi::c_char,
        99 as std::ffi::c_char,
        104 as std::ffi::c_char,
        46 as std::ffi::c_char,
        99 as std::ffi::c_char,
        44 as std::ffi::c_char,
        118 as std::ffi::c_char,
        32 as std::ffi::c_char,
        49 as std::ffi::c_char,
        46 as std::ffi::c_char,
        51 as std::ffi::c_char,
        32 as std::ffi::c_char,
        49 as std::ffi::c_char,
        57 as std::ffi::c_char,
        57 as std::ffi::c_char,
        55 as std::ffi::c_char,
        47 as std::ffi::c_char,
        48 as std::ffi::c_char,
        49 as std::ffi::c_char,
        47 as std::ffi::c_char,
        50 as std::ffi::c_char,
        56 as std::ffi::c_char,
        32 as std::ffi::c_char,
        50 as std::ffi::c_char,
        50 as std::ffi::c_char,
        58 as std::ffi::c_char,
        48 as std::ffi::c_char,
        56 as std::ffi::c_char,
        58 as std::ffi::c_char,
        50 as std::ffi::c_char,
        57 as std::ffi::c_char,
        32 as std::ffi::c_char,
        98 as std::ffi::c_char,
        49 as std::ffi::c_char,
        32 as std::ffi::c_char,
        69 as std::ffi::c_char,
        120 as std::ffi::c_char,
        112 as std::ffi::c_char,
        32 as std::ffi::c_char,
        36 as std::ffi::c_char,
        0,
    ]
};

pub static mut alphSwitchList: [switchlist_t; 41] = unsafe {
    [
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                71 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                78 as std::ffi::c_char,
                71 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                79 as std::ffi::c_char,
                87 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                79 as std::ffi::c_char,
                87 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                80 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                67 as std::ffi::c_char,
                79 as std::ffi::c_char,
                77 as std::ffi::c_char,
                80 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                68 as std::ffi::c_char,
                73 as std::ffi::c_char,
                82 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                68 as std::ffi::c_char,
                73 as std::ffi::c_char,
                82 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                69 as std::ffi::c_char,
                88 as std::ffi::c_char,
                73 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                69 as std::ffi::c_char,
                88 as std::ffi::c_char,
                73 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                71 as std::ffi::c_char,
                82 as std::ffi::c_char,
                65 as std::ffi::c_char,
                89 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                71 as std::ffi::c_char,
                82 as std::ffi::c_char,
                65 as std::ffi::c_char,
                89 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                71 as std::ffi::c_char,
                82 as std::ffi::c_char,
                65 as std::ffi::c_char,
                89 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                71 as std::ffi::c_char,
                82 as std::ffi::c_char,
                65 as std::ffi::c_char,
                89 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                65 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                65 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                80 as std::ffi::c_char,
                73 as std::ffi::c_char,
                80 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                80 as std::ffi::c_char,
                73 as std::ffi::c_char,
                80 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                76 as std::ffi::c_char,
                65 as std::ffi::c_char,
                68 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                76 as std::ffi::c_char,
                65 as std::ffi::c_char,
                68 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                71 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                71 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                82 as std::ffi::c_char,
                84 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                82 as std::ffi::c_char,
                84 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            episode: 1,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                76 as std::ffi::c_char,
                85 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                76 as std::ffi::c_char,
                85 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                67 as std::ffi::c_char,
                77 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                67 as std::ffi::c_char,
                77 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                71 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                71 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                71 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                71 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                71 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                71 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                72 as std::ffi::c_char,
                79 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                72 as std::ffi::c_char,
                79 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                76 as std::ffi::c_char,
                73 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                76 as std::ffi::c_char,
                73 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                65 as std::ffi::c_char,
                84 as std::ffi::c_char,
                89 as std::ffi::c_char,
                82 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                65 as std::ffi::c_char,
                84 as std::ffi::c_char,
                89 as std::ffi::c_char,
                82 as std::ffi::c_char,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                75 as std::ffi::c_char,
                73 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                75 as std::ffi::c_char,
                73 as std::ffi::c_char,
                78 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                86 as std::ffi::c_char,
                73 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                86 as std::ffi::c_char,
                73 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                87 as std::ffi::c_char,
                79 as std::ffi::c_char,
                79 as std::ffi::c_char,
                68 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                87 as std::ffi::c_char,
                79 as std::ffi::c_char,
                79 as std::ffi::c_char,
                68 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 2,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                80 as std::ffi::c_char,
                65 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                80 as std::ffi::c_char,
                65 as std::ffi::c_char,
                78 as std::ffi::c_char,
                69 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                82 as std::ffi::c_char,
                79 as std::ffi::c_char,
                67 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                82 as std::ffi::c_char,
                79 as std::ffi::c_char,
                67 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                50 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                87 as std::ffi::c_char,
                68 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                87 as std::ffi::c_char,
                68 as std::ffi::c_char,
                77 as std::ffi::c_char,
                69 as std::ffi::c_char,
                84 as std::ffi::c_char,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                73 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                66 as std::ffi::c_char,
                82 as std::ffi::c_char,
                73 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                77 as std::ffi::c_char,
                79 as std::ffi::c_char,
                68 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                77 as std::ffi::c_char,
                79 as std::ffi::c_char,
                68 as std::ffi::c_char,
                49 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                90 as std::ffi::c_char,
                73 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                90 as std::ffi::c_char,
                73 as std::ffi::c_char,
                77 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                54 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                84 as std::ffi::c_char,
                79 as std::ffi::c_char,
                78 as std::ffi::c_char,
                54 as std::ffi::c_char,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                84 as std::ffi::c_char,
                69 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                84 as std::ffi::c_char,
                69 as std::ffi::c_char,
                75 as std::ffi::c_char,
                0,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                77 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                66 as std::ffi::c_char,
                0,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                77 as std::ffi::c_char,
                65 as std::ffi::c_char,
                82 as std::ffi::c_char,
                66 as std::ffi::c_char,
                0,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                49 as std::ffi::c_char,
                83 as std::ffi::c_char,
                75 as std::ffi::c_char,
                85 as std::ffi::c_char,
                76 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            name2: [
                83 as std::ffi::c_char,
                87 as std::ffi::c_char,
                50 as std::ffi::c_char,
                83 as std::ffi::c_char,
                75 as std::ffi::c_char,
                85 as std::ffi::c_char,
                76 as std::ffi::c_char,
                76 as std::ffi::c_char,
                0,
            ],
            episode: 3,
        },
        switchlist_t {
            name1: [0 as std::ffi::c_char, 0, 0, 0, 0, 0, 0, 0, 0],
            name2: [0 as std::ffi::c_char, 0, 0, 0, 0, 0, 0, 0, 0],
            episode: 0,
        },
    ]
};

pub static mut switchlist: [std::ffi::c_int; (MAXSWITCHES * 2) as usize] =
    unsafe { std::mem::zeroed() }; // TODO: initializer not yet translated

pub static mut numswitches: std::ffi::c_int = unsafe { std::mem::zeroed() }; // TODO: initializer not yet translated

pub static mut buttonlist: [button_t; (MAXBUTTONS) as usize] = unsafe { std::mem::zeroed() }; // TODO: initializer not yet translated

pub unsafe extern "C" fn P_InitSwitchList() {
    unsafe { todo!("body not yet translated") }
}

pub unsafe extern "C" fn P_StartButton(
    line: *mut line_t,
    w: bwhere_e,
    texture: std::ffi::c_int,
    time: std::ffi::c_int,
) {
    unsafe { todo!("body not yet translated") }
}

pub unsafe extern "C" fn P_ChangeSwitchTexture(line: *mut line_t, useAgain: std::ffi::c_int) {
    unsafe { todo!("body not yet translated") }
}

pub unsafe extern "C" fn P_UseSpecialLine(
    thing: *mut mobj_t,
    line: *mut line_t,
    side: std::ffi::c_int,
) -> boolean {
    unsafe { todo!("body not yet translated") }
    todo!("fell off the end of a non-void C function")
}
