//! Filesystem/subprocess-touching bits of codegen: writing generated Rust
//! text to `doom_rs/src/*.rs`, generating `lib.rs`, and invoking `rustfmt`.
//! Kept separate from the rest of `codegen/` (which stays pure/unit-
//! testable with no filesystem dependency) - mirrors how `parser::corpus`
//! is the one module in the parser front end that touches the filesystem,
//! while everything else stays pure.
//!
//! `doom_rs/src/*.rs` and `lib.rs` are fully disposable and regenerated
//! wholesale on every run, never hand-edited: `write_all` first removes
//! every existing generated `.rs` file so a renamed/removed module doesn't
//! leave a stale file behind, then writes everything fresh.
//! `doom_rs/Cargo.toml` is hand-authored once and never touched here.

use std::io;
use std::path::{Path, PathBuf};

/// Crate-level lint attributes for the generated `lib.rs` preamble - this
/// is an unsafe transliteration, not idiomatic Rust: C identifiers keep
/// their own casing (`non_snake_case`/`non_camel_case_types`/
/// `non_upper_case_globals`), stub bodies have unused params, some modules
/// have unused imports (a `use crate::x::*;` glob whose contents happen not
/// to be referenced by every neighboring file), and pointer-heavy C ABI
/// shapes can look suspicious to `improper_ctypes` without actually being
/// wrong for this use case.
///
/// `recursion_limit` is raised well above the default (128): an `Enum`'s
/// implicit-successor variants each emit `PREV + 1` (see
/// `codegen::items::emit_enum` - zero evaluation on the codegen side,
/// rustc's own const-folding resolves the real value), and this corpus's
/// largest enum (`info.h`'s `statenum_t`) has 967 variants - a real corpus
/// build confirmed rustc's const-eval hits "queries overflow the depth
/// limit" at the default when such a constant is later used in a `usize`
/// array-length position (`[state_t; NUMSTATES as usize]`), which recurses
/// through the whole `PREV + 1` chain to evaluate. 8192 is comfortable
/// headroom above the worst real case.
const LIB_RS_PREAMBLE: &str = "\
// Generated by `transpiler --emit-rust` - do not hand-edit, regenerated
// wholesale on every run. See transpiler/src/codegen/ and
// /home/michael/.claude/plans/eager-marinating-axolotl.md.
#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
#![allow(dead_code, unused_variables, unused_imports)]
#![allow(improper_ctypes)]
#![recursion_limit = \"8192\"]

";

/// Builds `lib.rs`'s full text: the lint preamble plus one `pub mod {name};`
/// per generated module, sorted for deterministic output.
pub fn generate_lib_rs(module_names: &[String]) -> String {
    let mut sorted: Vec<&String> = module_names.iter().collect();
    sorted.sort();
    let mut out = LIB_RS_PREAMBLE.to_string();
    for name in sorted {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out
}

/// Removes every existing generated `.rs` file directly under `src_dir`
/// (non-recursive - `doom_rs/src/` is flat, one file per module) so a
/// module renamed or removed since the last run doesn't leave stale
/// content behind. `src_dir` itself must already exist (it does, as part
/// of the hand-authored `doom_rs/Cargo.toml` setup).
fn clear_generated_dir(src_dir: &Path) -> io::Result<()> {
    for entry in std::fs::read_dir(src_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            std::fs::remove_file(path)?;
        }
    }
    Ok(())
}

/// Writes every `(module_name, generated_text)` pair to `src_dir/{name}.rs`
/// plus a freshly generated `lib.rs`, clearing old generated files first
/// (see `clear_generated_dir`). Returns every path written (for the
/// caller to hand to `run_rustfmt`).
pub fn write_all(src_dir: &Path, modules: &[(String, String)]) -> io::Result<Vec<PathBuf>> {
    clear_generated_dir(src_dir)?;
    let mut written = Vec::new();
    for (name, text) in modules {
        let path = src_dir.join(format!("{name}.rs"));
        std::fs::write(&path, text)?;
        written.push(path);
    }
    let module_names: Vec<String> = modules.iter().map(|(name, _)| name.clone()).collect();
    let lib_path = src_dir.join("lib.rs");
    std::fs::write(&lib_path, generate_lib_rs(&module_names))?;
    written.push(lib_path);
    Ok(written)
}

/// Shells out to the `rustfmt` binary to pretty-print every written file in
/// one invocation. An external tool call, not a new Cargo dependency -
/// matches how this project already shells out to `cargo fmt`/`clippy` in
/// its own dev loop but has never added a codegen/formatting library
/// dependency. Best-effort: a missing `rustfmt` binary or a formatting
/// failure is reported but not fatal - the unformatted generated text is
/// still syntactically whatever codegen produced, just less pretty.
pub fn run_rustfmt(paths: &[PathBuf]) -> io::Result<()> {
    if paths.is_empty() {
        return Ok(());
    }
    // `rustfmt` invoked directly on file paths (not via `cargo fmt`) doesn't
    // read `doom_rs/Cargo.toml`'s `edition = "2024"` - it defaults to 2015,
    // which fails to even parse a `c"..."` C-string literal (added once
    // `codegen::macros` started emitting them for string-valued `#define`s).
    // Must match `doom_rs/Cargo.toml`'s edition exactly.
    let status = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .args(paths)
        .status()?;
    if !status.success() {
        eprintln!("warning: rustfmt exited with {status} - generated files may be unformatted");
    }
    Ok(())
}

#[cfg(test)]
mod tests;
